Merged with trunk
git-svn-id: svn+ssh://qeforge.qe-forge.org/svnroot/yambo-devel/branches/devel-andrea@4158 76a4dfbf-5f1f-0410-a543-a0282073b526

diff --git a/lib/archive/Makefile.loc b/lib/archive/Makefile.loc
--- a/lib/archive/Makefile.loc
+++ b/lib/archive/Makefile.loc
@@ -9,7 +9,18 @@
 #
 include ./package.list
 
-all: $(tarball_iotk) $(tarball_netcdf) $(tarball_etsf_io)
+all: $(tarball_libxc) $(tarball_iotk) $(tarball_netcdf) $(tarball_etsf_io)
+
+$(tarball_libxc):
+	wget -O $(tarball_libxc) $(url_libxc) > /dev/null 2>&1
+	@if test "`echo $$?`" -ne "0" ; then \
+		curl -o $(tarball_libxc) $(url_libxc) > /dev/null 2>&1 ; \
+	fi
+	@if test ! -s $(tarball_libxc) ; then \
+		echo "*** Unable to download LIBXC. Test whether curl or wget is installed and working," ; \
+		echo "*** if you have direct access to the internet." ; \
+		echo "*** If not, copy $(tarball_libxc) into extlibs/archive/" ; \
+	exit 1 ; fi
 
 $(tarball_iotk):
 	wget -O $(tarball_iotk) $(url_iotk) > /dev/null 2>&1
@@ -51,6 +62,7 @@ clean:
 
 clean_all:
 	if test ! -e keep-extlibs-stamp ; then \
+          if test -s $(tarball_libxc)   && test "$(keep_libxc)"   != "yes" ;  then rm $(tarball_libxc)    ; fi ; \
           if test -s $(tarball_iotk)    && test "$(keep_iotk)"    != "yes" ;  then rm $(tarball_iotk)    ; fi ; \
           if test -s $(tarball_netcdf)  && test "$(keep_netcdf)"  != "yes" ;  then rm $(tarball_netcdf)  ; fi ; \
           if test -s $(tarball_etsf_io) && test "$(keep_etsf_io)" != "yes" ;  then rm $(tarball_etsf_io) ; fi ; \
